defaults: &DEFAULTS
  working_directory: /go/src/github.com/binarydud
  docker:
    - image: circleci/golang:1.10.3-stretch-node
  environment:
    GOCACHE: /tmp
    DEP_VERSION: 0.4.1
  
  #working_directory: /go/src/github.com/racker/janus-passport
  

version: 2
jobs:
  setup_project:
    <<: *DEFAULTS
    steps:
      - checkout
      - run: ls -latr
      - persist_to_workspace:
          root: /go/src/github.com/binarydud
          paths:
              - .
  build:
    <<: *DEFAULTS
    steps:
      - attach_workspace:
          at: /go/src/github.com/binarydud
      - run: ls -latr

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup_project
      - build:
          requires:
            - setup_project
