defaults: &DEFAULTS
  working_directory: /go/src/github.com/binarydud
  docker:
    - image: circleci/golang:1.10.3-stretch-node
  environment:
    GOCACHE: /tmp
    DEP_VERSION: 0.4.1
  
  #working_directory: /go/src/github.com/racker/janus-passport
  

version: 2
jobs:
  setup:
    <<: *DEFAULTS
    steps:
      - checkout
      - run: ls -latr
      - restore_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
      - run:
          name: download-libraries
          command: |
            if [ ! -d /go/src/github.com/binarydud/gotest/vendor ]; then
                curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o /go/bin/dep
                chmod +x /go/bin/dep
                /go/bin/dep ensure
            fi
      - save_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
              - /go/src/github.com/binarydud/gotest/vendor
      - persist_to_workspace:
          root: /go/src/github.com/binarydud
          paths:
              - .
  build:
    <<: *DEFAULTS
    steps:
      - attach_workspace:
          at: /go/src/github.com/binarydud
      - run: ls -latr
      - run: ls -latr vendor

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - build:
          requires:
            - setup
